# Generated by Django 4.2.1 on 2023-06-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
    ]
