# Generated by Django 4.2.2 on 2023-06-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_applications_logo_applications_serveur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serveurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('processeur', models.CharField(choices=[('i3', 'i3'), ('i5', 'i5'), ('i7', 'i7'), ('i9', 'i9'), ('ryzen3', 'ryzen3'), ('ryzen5', 'ryzen5'), ('ryzen7', 'ryzen7')], max_length=20, null=True)),
                ('memoire', models.CharField(choices=[('64Go', '64Go'), ('32Go', '32Go'), ('16Go', '16Go'), ('8Go', '8Go')], max_length=20, null=True)),
                ('stockage', models.CharField(choices=[('1To', '1To'), ('512Go', '512Go'), ('256Go', '256Go'), ('128Go', '128Go'), ('64Go', '64Go'), ('32Go', '32Go')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Apache', 'Apache'), ('SQL', 'SQL'), ('DNS', 'DNS'), ('Proxy', 'Proxy'), ('Imap', 'Imap')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='fiches',
            name='nom',
        ),
        migrations.AddField(
            model_name='fiches',
            name='applications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='adminsite.applications'),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('memoire_use', models.CharField(max_length=8)),
                ('memoire_vive', models.CharField(max_length=8)),
                ('serveur_lancement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serveur_lancement', to='adminsite.serveurs')),
            ],
        ),
        migrations.AddField(
            model_name='serveurs',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='adminsite.types'),
        ),
        migrations.AddField(
            model_name='fiches',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='adminsite.services'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='serveur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serveur', to='adminsite.serveurs'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='utilisateurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='adminsite.utilisateurs'),
        ),
    ]
