# Generated by Django 4.2.2 on 2023-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0004_serveurs_types_utilisateurs_remove_fiches_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
