# Generated by Django 4.2.1 on 2023-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_alter_applications_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='memoire_use',
            new_name='stockage_use',
        ),
        migrations.AlterField(
            model_name='applications',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Fiches',
        ),
    ]
