# Generated by Django 4.2.1 on 2023-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0006_rename_memoire_use_services_stockage_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='logo',
            field=models.ImageField(default='media/images/casimir.png', null=True, upload_to='images/'),
        ),
    ]
